language: node_js
env:
  matrix:
  - CXX=g++-4.8
node_js:
- 6.2.2
script:
- cd docker/backend-src
- npm install
- npm test
- cd -
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_f2265a680160_key -iv $encrypted_f2265a680160_iv
  -in deploy-files.tar.bz2.enc -out deploy-files.tar.bz2 -d
- tar xvf deploy-files.tar.bz2
- mv deploy-files/* .
- cp config.ini docker/backend-src
- chmod 600 deploy_key
- cp deploy_key ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
after_success:
- echo "Host mr-calen.eu" >> ~/.ssh/config
- echo "    StrictHostKeyChecking no" >> ~/.ssh/config
- rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ ci@mr-calen.eu:/home/ci/calentron
- sh launch-docker.sh
notifications:
  slack:
    secure: i+X/NJ6/yVexTEWYukKlSlUiEfWrZPau/C7ODalAisPAqg4RUazkQ7oqx5sRt5cyEs6+QGfrVKukr6IbVeR5GtdyPE5js5R1Y3PNGhjjhu/Gw38T6U85UKf9p638C3puVblN9oggI/XL8edsSQptA17Glh8bzN49KxACZCZhUZ4BnhPlkDep0HBOz2DQAa97+wm4yeziHVvRmUxsbVH8F3SszAlllXcmLrs3QKaRY2JRPP1yoqtmyherYBlj0zX/iwHmzOcOleDl7qcLloFTROdI6tROAW/5vdRjs9L9VoNmMY8w9o1aEdiwwpz+UbQfdrBs4cuGb0mkhPwkQuThi+VbVAOvzR/RGOczmUyra9Qb5iBZEXM2ja465igbouPuWUfoX2KwXlLWeZW3mz8ZirLzQIpItsbbYKk4g8vZLfagPZGHen8i1Ib/nb2ZNvVtoJoyfQb7kcti4vDuJlRLwj/+CTQWkVmNGxZK50xQpnaikShOJjZVgb6OKHEZXnd/BVS6nMo3HctrFrAfc45WinGxXnY8rHDr3j5D4//sJksRxVJWNl+oLvd3LrusAe/OE9frubW4Qy3TGG6KN+7Uc1aY/w+TvqC7dulVq/1F0j4oEtoLT24CS24L4q4Mi630zk4tbE3FN3p/ddJCrhdQzxHf3Mp2VN8+Pjx194wyMPo=
