mysql:
  image: "mysql:5.6"
  container_name: db
  environment:
     MYSQL_ROOT_PASSWORD: calentron
     MYSQL_DATABASE: calentron
     PING_URL: HIDDEN_PING
     CAH_URL: HIDDEN_CAH
     WEATHER_KEY: HIDDEN_WEATHER
node:
  build: .
  container_name: backend
  ports:
    - "3000:3000"
  links:
    - mysql
